import type { Metadata } from "next";
import "./globals.css";

import { Inter as FontSans } from "next/font/google";
import { cn } from "@/lib/utils";

import WhatsAppButton from "@/components/WhatsAppButton";
import InstagramAppButton from "@/components/InstagramAppButton"; 

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        {children}
        {/* WhatsApp sağ alt köşede */}
        <div className="fixed bottom-4 right-4 z-50">
          <WhatsAppButton />
        </div>
        {/* Instagram sağ alt köşede, WhatsApp'ın biraz üstünde */}
        <div className="fixed bottom-5 right-20 z-50">
          <InstagramAppButton />
        </div>
      </body>
    </html>
  );
}
